### ISSUE TITLE
Betrayel [Quest]

### ISSUE THREAD

**Issue by xXDzepniXx** [perru/wowmania#1]
The quest runs fine, except the issue is when you go over to the platform where you fight Drakuru with his 500k HP on a platform at the top of Voltarus. Everything works fine, you can control the minion with 200k HP and (presumably) defeat him, the issue is that there is a entity called "Blight Fog" or "Fog of Blight" something like that. This is casted right after your disguise wears off, and it's on every part of the platform, you take 1200 damage, and it kills you in 10-20 seconds. I believe the place where Drakuru stands there's suppose to be no fog, on the other hand there is. Every inch of that place is covered with a fog, and you get killed. Making the quest impossible to do. So that is the issue.

**Comment by perru** [comment]
Hi,

Maybe you speak about http://www.wow-mania.com/. It's not this repo, here it's for http://wowmania.fr/.

I don't know if they have a GitHub or something but maybe you can try to join them in their forums.

Lock :).
