### ISSUE TITLE
The Oculus | Boss | Drakos the Interrogator

### ISSUE THREAD

**Issue by xXDzepniXx** [perru/wowmania#2]
If this isn't already made, go ahead and delete this; Drakos the Interrogator is a bugged boss in The Oculus dungeon, when you start him he has a bunch of orb things flying a round him, which make explosions, and it's endlesss, it takes a huge chunk of your health, and kills you very fast. You can't get close without dying.

That's pretty much it.

**Comment by perru** [comment]
Hi,

Maybe you speak about http://www.wow-mania.com/. It's not this repo, here it's for http://wowmania.fr/.

I don't know if they have a GitHub or something but maybe you can try to join them in their forums.

Lock :).
