### ISSUE TITLE
The Argent tournament

### ISSUE THREAD

**Issue by martonicx** [perru/wowmania#3]
There is a Daily quest named: Among the Champions. It Is bugged. The Silvermoon Champion gives you 1 Mark of Champion, but after that non of the npc-s give you the remaining 3 that you need to complete the quest. Thank you Forward.

**Comment by perru** [comment]
Hi,

Maybe you speak about http://www.wow-mania.com/. It's not this repo, here it's for http://wowmania.fr/.

I don't know if they have a GitHub or something but maybe you can try to join them in their forums.

Lock :).
