### ISSUE TITLE
Pending sales from the Auction House

### ISSUE THREAD

**Issue by ricamora** [perru/wowmania#4]
I'm had the issue with pending sales on multiple occasions when i get the alert from the auction house stating a buyer has been found for my items, yet a number of them are put as "sale pending" and others of the same item are sold and the gold is transferred immediately. I've noticed that the majority of the sales labeled "sale pending" end of disappearing from the auction house and my mail without ever transferring the money. this issue has caused me to lose several hundred gold.

**Comment by perru** [comment]
Hi,

Maybe you speak about http://www.wow-mania.com/. It's not this repo, here it's for http://wowmania.fr/.

I don't know if they have a GitHub or something but maybe you can try to join them in their forums.

Lock :).
